### ISSUE TITLE
Missing .env file

### ISSUE THREAD

**Issue by brianzelip** [gdiggs/rayons#488]
Cool project! I'm new to ruby and rails, and a collector so want to dig under the hood and deploy locally.

Cloning and running `make dev` gives this error:

```
rayons/.env: no such file or directory
make: *** [dev] Error 14
```

I assume [app.json](https://github.com/gdiggs/rayons/blob/main/app.json#L6) details what's needed in .env?
It might be useful to include a sample.env.

**Comment by gdiggs** [comment]
Hey @brianzelip I added an example env file and a line to the README!
